# Generated by Django 5.1 on 2024-08-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contactformmessage_status_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='youtube',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
