# Generated by Django 5.1 on 2024-08-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_setting_linkedin_setting_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_position', models.CharField(max_length=100)),
                ('background_image', models.ImageField(upload_to='backgrounds/')),
                ('author_image', models.ImageField(upload_to='authors/')),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
